--Initial Creation (10-Jan-2023) COURSE_YEARS:



/*table creation script for "COURSE_YEARS"*/


CREATE TABLE  "COURSE_YEARS" 
   (	"CURRECT_COURSE_ID" NUMBER, 
	"CURRECT_CRSYEAR_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"CUST_YEAR_ID" VARCHAR2(30) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"CUST_YEAR_CODE" VARCHAR2(30) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"YEAR_TITLE" VARCHAR2(100) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"DDF" VARCHAR2(10) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"UDF1" VARCHAR2(500) COLLATE "USING_NLS_COMP", 
	"CUST_SORT" NUMBER, 
	"LAST_USER" VARCHAR2(30) COLLATE "USING_NLS_COMP", 
	"LAST_DATE" DATE, 
	 CONSTRAINT "CRYR_PK" PRIMARY KEY ("CURRECT_CRSYEAR_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CRYR_UK" UNIQUE ("CURRECT_COURSE_ID", "CUST_YEAR_ID", "CUST_YEAR_CODE")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
   
 
 /*sequence creation script for "COURSE_YEARS"*/


 CREATE SEQUENCE   "COURSE_YEARS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL
 
 
 /*trigger creation script for "COURSE_YEARS"*/


CREATE OR REPLACE EDITIONABLE TRIGGER  "COURSE_YEARS_IUTR" 
BEFORE INSERT or update
ON COURSE_YEARS
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
DECLARE
BEGIN
	:NEW.last_date := SYSDATE;
	if :NEW.last_user is null
	then
		:NEW.last_user := NVL(v('APP_USER'), USER);
	end if;	
EXCEPTION
	WHEN OTHERS THEN
		Raise_Application_Error(-20101,'Unexpected system error at level iutr(Course year group) : '||SQLCODE||' --- '||SQLERRM, TRUE);
END COURSE_YEARS_IUTR;

/
ALTER TRIGGER  "COURSE_YEARS_IUTR" ENABLE
/

