--Initial Creation (10-Jan-2023) COURSEYEAR_GROUPS:


/*table creation script for "COURSEYEAR_GROUPS"*/


CREATE TABLE  "COURSEYEAR_GROUPS" 
   (	"CURRECT_CRSYEAR_ID" NUMBER, 
	"CURRECT_TWINDOW_ID" NUMBER, 
	"CURRECT_GRP_TYPE_ID" NUMBER, 
	"CURRECT_GROUP_ID" NUMBER, 
	"GROUP_TITLE" VARCHAR2(80) COLLATE "USING_NLS_COMP", 
	"DISPLAY_POSITION" NUMBER, 
	"LAST_USER" VARCHAR2(30) COLLATE "USING_NLS_COMP", 
	"LAST_DATE" DATE, 
	 CONSTRAINT "CYG_PK" PRIMARY KEY ("CURRECT_GROUP_ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
   
   
   
   /*sequence creation script for "COURSEYEAR_GROUPS"*/

   
 CREATE SEQUENCE   "COURSEYEAR_GROUPS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL



   
   /*trigger creation script for "COURSEYEAR_GROUPS"*/

   
  CREATE OR REPLACE EDITIONABLE TRIGGER  "COURSEYEAR_GROUPS_IUTR" 
BEFORE INSERT or update
ON courseyear_groups
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
DECLARE
BEGIN

	:NEW.last_date := SYSDATE;

	if :NEW.last_user is null
	then
		:NEW.last_user := NVL(v('APP_USER'), USER);
	end if;	

EXCEPTION

	WHEN OTHERS THEN
		Raise_Application_Error(-20101,'Unexpected system error at level iutr(Course year group) : '||SQLCODE||' --- '||SQLERRM, TRUE);

END courseyear_groups_IUTR;

/
ALTER TRIGGER  "COURSEYEAR_GROUPS_IUTR" ENABLE
/

