--Initial Creation (10-Jan-2023) COURSEYEAR_STATS:



/*table creation script for "COURSEYEAR_STATS"*/


CREATE TABLE  "COURSEYEAR_STATS" 
   (	"CURRECT_CYST_ID" NUMBER, 
	"CURRECT_DATASET_ID" NUMBER, 
	"CURRECT_OWNER_ID" NUMBER, 
	"CURRECT_CRSYEAR_ID" NUMBER, 
	"CONTACT_HOURS" NUMBER, 
	"CONTRA_HOURS" NUMBER, 
	"RAG_RED" NUMBER, 
	"RAG_AMBER" NUMBER, 
	"RAG_GREEN" NUMBER, 
	"RECENT_UPDATE" DATE, 
	"LAST_USER" VARCHAR2(30) COLLATE "USING_NLS_COMP", 
	"LAST_DATE" DATE
   )  DEFAULT COLLATION "USING_NLS_COMP"
   
   

/*sequence creation script for "COURSEYEAR_STATS"*/

   
 CREATE SEQUENCE   "COURSEYEAR_STATS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL



/*trigger creation script for "COURSEYEAR_STATS"*/

   
CREATE OR REPLACE EDITIONABLE TRIGGER  "COURSEYEAR_STATS_IUTR" 
BEFORE INSERT or update
ON COURSEYEAR_STATS
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
DECLARE
BEGIN
	:NEW.last_date := SYSDATE;
	if :NEW.last_user is null
	then
		:NEW.last_user := NVL(v('APP_USER'), USER);
	end if;	
EXCEPTION
	WHEN OTHERS THEN
		Raise_Application_Error(-20101,'Unexpected system error at level iutr(Course year group) : '||SQLCODE||' --- '||SQLERRM, TRUE);
END COURSEYEAR_STATS_IUTR;

/
ALTER TRIGGER  "COURSEYEAR_STATS_IUTR" ENABLE
/

