--Initial Creation (10-Jan-2023) COURSES:


/*table creation script for "COURSES"*/


CREATE TABLE  "COURSES" 
   (	"CURRECT_DATASET_ID" NUMBER, 
	"CURRECT_OWNER_ID" NUMBER, 
	"CURRECT_COURSE_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"CUST_COURSE_ID" VARCHAR2(30) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"CUST_COURSE_CODE" VARCHAR2(30) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"INSTANCE" VARCHAR2(30) COLLATE "USING_NLS_COMP", 
	"PATHWAY" VARCHAR2(30) COLLATE "USING_NLS_COMP", 
	"INTAKE" VARCHAR2(30) COLLATE "USING_NLS_COMP", 
	"STUDY_LEVEL" VARCHAR2(30) COLLATE "USING_NLS_COMP", 
	"UDF_SEPERATOR" VARCHAR2(30) COLLATE "USING_NLS_COMP", 
	"FULL_TIME" VARCHAR2(1) COLLATE "USING_NLS_COMP", 
	"REMOTE_LEARNING" VARCHAR2(1) COLLATE "USING_NLS_COMP", 
	"COURSE_TITLE" VARCHAR2(100) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"PATHWAY_TITLE" VARCHAR2(100) COLLATE "USING_NLS_COMP", 
	"INSTANCE_TITLE" VARCHAR2(100) COLLATE "USING_NLS_COMP", 
	"INTAKE_TITLE" VARCHAR2(100) COLLATE "USING_NLS_COMP", 
	"STATUS" VARCHAR2(30) COLLATE "USING_NLS_COMP", 
	"UCAS_CODE1" VARCHAR2(30) COLLATE "USING_NLS_COMP", 
	"UCAS_CODE2" VARCHAR2(30) COLLATE "USING_NLS_COMP", 
	"DDF_SINGLE_LINE" VARCHAR2(150) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"DDF_MULTI_LINE_1" VARCHAR2(150) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"DDF_MULTI_LINE_2" VARCHAR2(150) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"UDF1" VARCHAR2(500) COLLATE "USING_NLS_COMP", 
	"UDF2" VARCHAR2(500) COLLATE "USING_NLS_COMP", 
	"UDF3" VARCHAR2(500) COLLATE "USING_NLS_COMP", 
	"UDF4" VARCHAR2(500) COLLATE "USING_NLS_COMP", 
	"CUST_SORT" NUMBER, 
	"LAST_USER" VARCHAR2(30) COLLATE "USING_NLS_COMP", 
	"LAST_DATE" DATE, 
	 CONSTRAINT "CRS_PK" PRIMARY KEY ("CURRECT_COURSE_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CRS_UK" UNIQUE ("CURRECT_OWNER_ID", "CUST_COURSE_ID", "CUST_COURSE_CODE", "INSTANCE", "PATHWAY", "INTAKE", "STUDY_LEVEL", "UDF_SEPERATOR")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
   
   
   
   
/*sequence creation script for "COURSES"*/

 CREATE SEQUENCE   "COURSES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL
 
 
 
 /*trigger creation script for "COURSES"*/
 
 
CREATE OR REPLACE EDITIONABLE TRIGGER  "COURSES_IUTR" 
BEFORE INSERT or update
ON courses
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
DECLARE
BEGIN

	:NEW.last_date := SYSDATE;

	if :NEW.last_user is null
	then
		:NEW.last_user := NVL(v('APP_USER'), USER);
	end if;	

EXCEPTION

	WHEN OTHERS THEN
		Raise_Application_Error(-20101,'Unexpected system error at level iutr(Course) : '||SQLCODE||' --- '||SQLERRM, TRUE);

END courses_IUTR;

/
ALTER TRIGGER  "COURSES_IUTR" ENABLE
/

