--Initial Creation (10-Jan-2023) MODULES:



/*table creation script for "MODULES"*/


CREATE TABLE  "MODULES" 
   (	"CURRECT_DATASET_ID" NUMBER, 
	"CURRECT_OWNER_ID" NUMBER, 
	"CURRECT_TWINDOW_ID" NUMBER, 
	"CURRECT_MODULE_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"CUST_MODULE_ID" VARCHAR2(30) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"CUST_MODULE_CODE" VARCHAR2(30) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"INSTANCE_ID" VARCHAR2(30) COLLATE "USING_NLS_COMP", 
	"INSTANCE_CODE" VARCHAR2(30) COLLATE "USING_NLS_COMP", 
	"STUDY_LEVEL" VARCHAR2(30) COLLATE "USING_NLS_COMP", 
	"UDF_SEPERATOR" VARCHAR2(30) COLLATE "USING_NLS_COMP", 
	"MODULE_TITLE" VARCHAR2(100) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"INSTANCE_TITLE" VARCHAR2(100) COLLATE "USING_NLS_COMP", 
	"STATUS" VARCHAR2(30) COLLATE "USING_NLS_COMP", 
	"CREDITS" NUMBER, 
	"WEEKLY_HOURS" NUMBER, 
	"MODULE_CODE_DDF" VARCHAR2(15) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"MODULE_TITLE_DDF" VARCHAR2(100) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"UDF1" VARCHAR2(500) COLLATE "USING_NLS_COMP", 
	"UDF2" VARCHAR2(500) COLLATE "USING_NLS_COMP", 
	"UDF3" VARCHAR2(500) COLLATE "USING_NLS_COMP", 
	"UDF4" VARCHAR2(500) COLLATE "USING_NLS_COMP", 
	"CUST_SORT" NUMBER, 
	"LAST_USER" VARCHAR2(30) COLLATE "USING_NLS_COMP", 
	"LAST_DATE" DATE, 
	 CONSTRAINT "MOD_PK" PRIMARY KEY ("CURRECT_MODULE_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "MOD_UK" UNIQUE ("CURRECT_OWNER_ID", "CUST_MODULE_ID", "CUST_MODULE_CODE", "INSTANCE_ID", "INSTANCE_CODE", "STUDY_LEVEL", "UDF_SEPERATOR", "CURRECT_TWINDOW_ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"



/*sequence creation script for "MODULES"*/

   
 CREATE SEQUENCE   "MODULES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL

 
 /*trigger creation script for "MODULES"*/
 
 

CREATE OR REPLACE EDITIONABLE TRIGGER  "MODULES_IUTR" 
BEFORE INSERT or update
ON MODULES
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
DECLARE
BEGIN

	:NEW.last_date := SYSDATE;

	if :NEW.last_user is null
	then
		:NEW.last_user := NVL(v('APP_USER'), USER);
	end if;	

EXCEPTION

	WHEN OTHERS THEN
		Raise_Application_Error(-20101,'Unexpected system error at level iutr(Course year group) : '||SQLCODE||' --- '||SQLERRM, TRUE);

END MODULES_IUTR;

/
ALTER TRIGGER  "MODULES_IUTR" ENABLE
/

   