--Initial Creation (10-Jan-2023) TEMP_COURSE_STRUCTURE:


/*table creation script for "TEMP_COURSE_STRUCTURE"*/


CREATE GLOBAL TEMPORARY TABLE  "TEMP_COURSE_STRUCTURE" 
   (	"CURRECT_GROUP_ID" NUMBER, 
	"CURRECT_TWINDOW_ID" NUMBER, 
	"CURRECT_GRP_TYPE_ID" NUMBER, 
	"GROUP_TITLE" VARCHAR2(80) COLLATE "USING_NLS_COMP", 
	"DISPLAY_POSITION" NUMBER, 
	"CURRECT_MODULE_ID" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" ON COMMIT DELETE ROWS
/



/*sequence creation script for "TEMP_COURSE_STRUCTURE"*/


 CREATE SEQUENCE   "TEMP_COURSE_STRUCTURE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL


