--Initial Creation (10-Jan-2023) TERMS:


/*table creation script for "TERMS"*/


CREATE TABLE  "TERMS" 
   (	"CURRECT_DATASET_ID" NUMBER, 
	"TERM" VARCHAR2(50) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"APP_ITEM" VARCHAR2(50) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"CUST_TERM" VARCHAR2(50) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"CUST_TERM_SHORT" VARCHAR2(10) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"LAST_USER" VARCHAR2(30) COLLATE "USING_NLS_COMP", 
	"LAST_DATE" DATE, 
	 CONSTRAINT "TERM_PK" PRIMARY KEY ("CURRECT_DATASET_ID", "TERM")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
   
   
   
   
   /*sequence creation script for "TERMS"*/


 CREATE SEQUENCE   "TERMS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL




/*trigger creation script for "TERMS"*/


CREATE OR REPLACE EDITIONABLE TRIGGER  "TERMS_IUTR" 
BEFORE INSERT or update
ON terms
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
DECLARE
BEGIN

	:NEW.last_date := SYSDATE;

	if :NEW.last_user is null
	then
		:NEW.last_user := NVL(v('APP_USER'), USER);
	end if;	

EXCEPTION

	WHEN OTHERS THEN
		Raise_Application_Error(-20101,'Unexpected system error at level iutr(Term) : '||SQLCODE||' --- '||SQLERRM, TRUE);

END terms_IUTR;

/
ALTER TRIGGER  "TERMS_IUTR" ENABLE
/
   